version: "3"
services:
  extserver:
    build: 
      context: .
      dockerfile: docker/extserver/Dockerfile
    container_name: extserver
    volumes:
      - ./src/extserver/:/home/appuser/app
      - ./src/ssh_keys:/home/appuser/.ssh:ro
    environment:
      LC_ALL: C.UTF-8
    ports:
      - "8090:8090"
      
  intserver:
    build: 
      context: .
      dockerfile: docker/intserver/Dockerfile
    container_name: intserver
    volumes:
      - ./src/ssh_keys:/home/ctfuser/.ssh:ro
    environment:
      LC_ALL: C.UTF-8
    networks:
      - isolated_network

networks:
  isolated_network:
    driver: bridge
    internal: true