version: "3"
services:
  extserver:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/extserver/Dockerfile
      args:
        FLAG_EXTSERVER: ${FLAG_EXTSERVER:-flag{set_FLAG_EXTSERVER_in_dotenv}}
    container_name: extserver
    volumes:
      - ./src/extserver/:/home/flaguser/app
    environment:
      LC_ALL: C.UTF-8
    ports:
      - "8090:8090"
      - "2222:22"
    networks:
      - external_network
      
  intserver:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/intserver/Dockerfile
    container_name: intserver
    environment:
      LC_ALL: C.UTF-8
    networks:
      - external_network
      - internal_network

  flagserver:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/flagserver/Dockerfile
      args:
        FLAG_FLAGSERVER: ${FLAG_FLAGSERVER:-flag{set_FLAG_FLAGSERVER_in_dotenv}}
    container_name: flagserver
    environment:
      LC_ALL: C.UTF-8
    networks:
      - internal_network

networks:
  external_network:
    driver: bridge
  internal_network:
    driver: bridge
    internal: true