version: "3"
services:
  extserver:
    build: 
      context: .
      dockerfile: docker/extserver/Dockerfile
    container_name: extserver
    volumes:
      - ./src/extserver/:/home/appuser/app
    environment:
      LC_ALL: C.UTF-8
    ports:
      - "8090:8090"
      - "2222:22"
    networks:
      - ctf_network
      
  intserver:
    build: 
      context: .
      dockerfile: docker/intserver/Dockerfile
    container_name: intserver
    environment:
      LC_ALL: C.UTF-8
    networks:
      - ctf_network

networks:
  ctf_network:
    driver: bridge